#!/usr/bin/env node

// * Make it fail with invalid params

var nopt = require('nopt');
var log = require('npmlog');
var pkg = require('./package.json');
var mfpcliext = {};

var opts = nopt({
    debug: Boolean,
    verbose: Boolean
}, {
    d: '--debug',
    v: '--verbose'
});

if(opts.debug) {
    log.level = 'silly';
} else if(opts.verbose) {
    log.level = 'verbose'
} else {
    log.level = 'warn'
}

log.heading = pkg.name;

mfpcliext.argv = opts.argv.remain;

if (mfpcliext.argv[0]) {
    mfpcliext.action = mfpcliext.argv.shift();
} else {
    mfpcliext.action = 'help';
}

log.silly("Action is: " + mfpcliext.action);

if (mfpcliext.action === 'help') {
    console.log("Help!");
} else {
    log.error("Unknown command");
}
