#!/usr/bin/env node

var child_process = require('child_process');
var fs = require('fs');
var log = require('npmlog');
var nopt = require('nopt');
var path = require('path');

var pkg = require('./package.json');

var mfpcliext = {};

mfpcliext.XCODE_LOCATION = "/Applications/XCode.app";
mfpcliext.CLI_LOCATION = "/Applications/IBM/MobileFirst-CLI/mfp";
mfpcliext.SERVER_LOCATION = "~/.ibm/mobilefirst/6.3.0/server/";

var opts = nopt({
    debug: Boolean,
    verbose: Boolean,
    help: Boolean
}, {
    d: '--debug',
    v: '--verbose',
    h: '--help',
});

if(opts.debug) {
    log.level = 'silly';
} else if(opts.verbose) {
    log.level = 'verbose';
} else {
    log.level = 'warn';
}

log.heading = pkg.name;

mfpcliext.argv = opts.argv.remain;

if (mfpcliext.argv[0]) {
    mfpcliext.action = mfpcliext.argv.shift();
} else {
    mfpcliext.action = 'help-ext';
}

if(opts.help) {
    showHelp();
} else {
    mfpcliext.action = mfpcliext.action.toLowerCase();

    log.silly("Action is: " + mfpcliext.action);

    if (mfpcliext.action === 'help-ext') {
        showHelp();
    } else if(mfpcliext.action === 'native-ide') {
        log.verbose("About to open native IDE");
        appDir = findMfpApp();
        log.silly("App dir is: " + appDir);
        if(appDir === null) {
            log.error("Cannot find mfp application");
        } else {
            xcode = child_process.spawn('open', ['-a', mfpcliext.XCODE_LOCATION, path.join(appDir, mfpcliext.argv[0], "native")]);
        }
    } else {
        mfp = child_process.spawn(mfpcliext.CLI_LOCATION, [mfpcliext.action].concat(mfpcliext.argv), { stdio: 'inherit' });
    }
}

function findMfpApp() {
    var pathSoFar = process.cwd();

    while(!fs.existsSync(path.join(pathSoFar, 'application-descriptor.xml'))) {
        var newPath = path.dirname(pathSoFar);
        if(newPath === pathSoFar) {
            pathSoFar = null;
            break;
        } else {
            pathSoFar = newPath;
        }
    }

    return pathSoFar;
}

function showHelp() {
    console.log("This is the mfp-cli-ext utility. It is an unofficial utility which builds " +
                "on top of the mfp utility for the IBM MobileFirst Platform Foundation here: " +
                "https://developer.ibm.com/mobilefirstplatform/install/#clui. More detailed " +
                "documentation is to come. For the time being, please refer to" +
                "https://github.com/andrewferrier/mfp-cli-ext/blob/master/README.md");
}
